import { fr } from "./fr";
export const en: typeof fr = {
  locale: "en", nav: { home: "Home", club: "The Club", menu: "Menu", gallery: "Gallery", contact: "Contact", find: "Find us" },
  common: { discover: "Discover the Club", menu: "View the menu", call: "Call", directions: "Directions", hours: "Opening hours", unconfirmed: "To be confirmed", follow: "Follow on Instagram", close: "Close", all: "All" },
  home: { strap: "Pizza · Drinks · Wine · Good Times", title: "Your spot in Geneva for food, drinks and good times.", description: "Pizza, drinks, wine and a great atmosphere in the heart of Geneva.", label: "Espresso Club · Geneva", introTitle: "Not a coffee shop.\nA place where the night begins.", intro1: "Espresso Club is a social spot in the heart of Pâquis where people come for pizza, drinks, dinner and good times with friends.", intro2: "Pizza, pasta, wine, drinks and a laid-back atmosphere in one of Geneva’s liveliest neighbourhoods.", pizzaTitle: "Pizza at the centre of the table.", pizzaText: "From classics to more generous creations, our pizzas belong with your evenings, your drinks and your friends.", pizzasCta: "See the pizzas", drinksTitle: "One drink. Then maybe another.", drinksText: "Wine, cocktails, beer and drinks to start the night or keep it going.", drinksCta: "Discover", vibeTitle: "Come for the pizza.\nStay for the vibe.", vibeText: "A lively, laid-back address in the heart of Pâquis.", manifesto: ["GOOD FOOD.","GOOD DRINKS.","GOOD PEOPLE.","GOOD TIMES."], manifestEnd: "That’s Espresso Club.", featured: "Our pizzas", featuredSub: "A few reasons to stay a little longer.", featuredCta: "Discover the full menu", duoTitle: "Pizza & drinks.\nThe perfect duo.", duoText: "A pizza on the table, a drink in hand and no reason to rush.", nightTitle: "Stay for the vibe.", nightText: "Espresso Club is an atmosphere too. A place to start the night, meet friends or simply enjoy a good drink over pizza.", instagram: "The Espresso Club vibe", instagramText: "Follow the nights, the pizzas and everything in between.", location: "Meet us in Pâquis." },
  club: { hero: "MORE THAN PIZZA.\nMORE THAN A BAR.", lead: "Espresso Club is a lively address in the heart of Pâquis.", text: "Come to eat, have a drink, meet friends and enjoy the night in a simple, urban and laid-back atmosphere.", blocks: ["THE FOOD","THE DRINKS","THE PLACE","THE VIBE"] },
  menu: { title: "The Menu", subtitle: "Choose what goes with your evening.", categories: { pizza: "Pizza", pasta: "Pasta", salades: "Salads", desserts: "Desserts", drinks: "Drinks" }, empty: "Our drinks selection is coming soon." },
  gallery: { title: "Gallery", subtitle: "The lights, the glasses and the nights in Pâquis.", filters: { all: "All", pizza: "Pizza", drinks: "Drinks", food: "Food", people: "People", atmosphere: "Atmosphere" } },
  contact: { title: "Meet us in Pâquis.", subtitle: "A question or thinking of stopping by? Write to us.", name: "Name", email: "Email", phone: "Phone", message: "Message", send: "Send", sent: "Thank you. Your message is ready to be sent.", address: "Address" },
  footer: { rights: "All rights reserved.", by: "Website by Triade Publicité" }
};