import { fr } from "./fr";
export const pt: typeof fr = {
  locale: "pt", nav: { home: "Início", club: "O Club", menu: "Cardápio", gallery: "Galeria", contact: "Contato", find: "Como chegar" },
  common: { discover: "Conhecer o Espresso Club", menu: "Ver o cardápio", call: "Ligar", directions: "Como chegar", hours: "Horários", unconfirmed: "A confirmar", follow: "Seguir no Instagram", close: "Fechar", all: "Tudo" },
  home: { strap: "Pizza · Drinks · Vinho · Bons Momentos", title: "Seu lugar em Genebra para comer, beber e aproveitar.", description: "Pizza, drinks, vinhos e boa atmosfera no coração de Genebra.", label: "Espresso Club · Genebra", introTitle: "Não somos uma cafeteria.\nSomos o lugar onde a noite começa.", intro1: "No coração de Pâquis, o Espresso Club é um lugar para encontrar amigos, tomar alguma coisa, comer uma boa pizza e aproveitar o momento.", intro2: "Pizza, pasta, vinhos, drinks e um ambiente descontraído em um dos bairros mais animados de Genebra.", pizzaTitle: "A pizza no centro da mesa.", pizzaText: "Dos clássicos às receitas mais generosas, nossas pizzas acompanham suas noites, seus drinks e seus momentos entre amigos.", pizzasCta: "Ver as pizzas", drinksTitle: "Um drink. E talvez mais um.", drinksText: "Vinhos, cocktails, cervejas e bebidas para começar a noite ou fazer ela durar.", drinksCta: "Descobrir", vibeTitle: "Venha pela pizza.\nFique pela vibe.", vibeText: "Um endereço animado e descontraído no coração de Pâquis.", manifesto: ["COMIDA BOA.","DRINKS BONS.","GENTE BOA.","BONS MOMENTOS."], manifestEnd: "Isso é Espresso Club.", featured: "Nossas pizzas", featuredSub: "Alguns motivos para ficar um pouco mais.", featuredCta: "Conhecer todo o cardápio", duoTitle: "Pizza & drinks.\nA dupla perfeita.", duoText: "Uma pizza na mesa, um drink na mão e nenhuma razão para ter pressa.", nightTitle: "Fique pela vibe.", nightText: "Espresso Club também é atmosfera. Um lugar para começar a noite, encontrar amigos ou simplesmente aproveitar um bom drink com pizza.", instagram: "A vibe do Espresso Club", instagramText: "Acompanhe as noites, as pizzas e tudo que acontece entre elas.", location: "A gente se encontra em Pâquis." },
  club: { hero: "MAIS QUE PIZZA.\nMAIS QUE UM BAR.", lead: "Espresso Club é um endereço cheio de vida no coração de Pâquis.", text: "Um lugar para comer, tomar um drink, encontrar amigos e curtir a noite em um ambiente simples, urbano e descontraído.", blocks: ["A COMIDA","OS DRINKS","O LUGAR","A VIBE"] },
  menu: { title: "O Cardápio", subtitle: "Escolha o que vai acompanhar sua noite.", categories: { pizza: "Pizzas", pasta: "Pasta", salades: "Saladas", desserts: "Sobremesas", drinks: "Drinks" }, empty: "Nossa seleção de drinks chega em breve." },
  gallery: { title: "Galeria", subtitle: "As luzes, as taças e as noites em Pâquis.", filters: { all: "Tudo", pizza: "Pizza", drinks: "Drinks", food: "Comida", people: "Pessoas", atmosphere: "Ambiente" } },
  contact: { title: "A gente se encontra em Pâquis.", subtitle: "Alguma pergunta ou pensando em passar por aqui? Escreva para nós.", name: "Nome", email: "Email", phone: "Telefone", message: "Mensagem", send: "Enviar", sent: "Obrigado. Sua mensagem está pronta para ser enviada.", address: "Endereço" },
  footer: { rights: "Todos os direitos reservados.", by: "Website by Triade Publicité" }
};